### PR TITLE
Fixed file mode and changed logging library

### PR DESCRIPTION
**Pull request by theSuess**
The files were at rwxr-xr-x, they now are rw-r--r--
Logging is now done with logrus which makes the user experience friendlier

### CODE REVIEW

**Comment by nym3r0s** [comment]
Can you explain why you set the permissions to 644 (rw-r--r--) ?
Also, using logrus will increase the dependency on external packages. I was thinking of keeping the external dependencies to a minimum.

**Comment by theSuess** [comment]
Changing the permission makes it a more secure approach. Those files do not need an execute flag.
If you want to keep dependencies at a minimum I'll remove logrus again

**Comment by nym3r0s** [comment]
Cool :+1:  Can you remove logrus? I wanted it to be as minimal as possible.

**Comment by theSuess** [comment]
Sure thing!

**Comment by nym3r0s** [comment]
Can you reset your commits and add only the commit where you have changed the file permissions ? 
I know this is not a big project, but I'm trying to keep my commit history as clean as possible. 
Doable?

**Comment by theSuess** [comment]
Done did it!

**Comment by nym3r0s** [comment]
@theSuess , Thank you! :+1:  :smile:

**Pull request merged**
