### PR TITLE
Moved go-http.go into the top level directory for a friendlier instal…

### PR DESCRIPTION
**Pull request by scottjbarr**
…lation.

This allows users to just do a "standard" installation. I've updated the README to suit.
Thanks for the cool little server :)

### CODE REVIEW

**Comment by nym3r0s** [comment]
Hey ! Thanks for contributing, I've been looking to clean up the repo for some time now. That includes moving the `go-http.go` file to the top level directory. Thanks :+1:

**Comment by scottjbarr** [comment]
You're welcome!

**Comment by nym3r0s** [comment]
@scottjbarr  I've cleaned up the repo. Any other suggestions?

**Comment by scottjbarr** [comment]
Looks great to me @GokulSrinivas . Nice work.

**Comment by nym3r0s** [comment]
:+1:  Thanks :smile:

**Pull request merged**
